/*
Hella Gutmann - macsDS (Data Services) - API collection

Testing DTCAPIAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package github.com/binhatch/go-macds

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_github.com/binhatch/go-macds_DTCAPIAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DTCAPIAPIService Dtcs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DTCAPIAPI.Dtcs(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
