/*
Hella Gutmann - macsDS (Data Services) - API collection

This document contains all relevant APIs for diagnostics (incl. DTCs), repair & maintenance information (RMI) and vehicle identification.

API version: V20240702-130718
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github.com/binhatch/go-macds

import (
	"encoding/json"
)

// checks if the VehicleInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VehicleInfo{}

// VehicleInfo struct for VehicleInfo
type VehicleInfo struct {
	// Can have values to further specify the data type presented. Can have values such as: flatrateunit (repair times), fuserelay, composition (placements and organisation of different elements on the vehicle), stco (ECU coding), periphery (relevant periphery components to the main component), wiringdiagram, techdata, \"techinfo\" (proprietary knowledge database of Hella Gutmann), \"componenttestvalues\", \"bulletin\", \"manual\", \"gdst\" (basic setting),  \"faultcode\", \"parameter\"
	Datatype *string `json:"datatype,omitempty"`
	// order
	Order *int32 `json:"order,omitempty"`
	// Contains structured texts to guide the interpretation of text values.
	Richtext []RichTextDTO `json:"richtext,omitempty"`
}

// NewVehicleInfo instantiates a new VehicleInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVehicleInfo() *VehicleInfo {
	this := VehicleInfo{}
	return &this
}

// NewVehicleInfoWithDefaults instantiates a new VehicleInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVehicleInfoWithDefaults() *VehicleInfo {
	this := VehicleInfo{}
	return &this
}

// GetDatatype returns the Datatype field value if set, zero value otherwise.
func (o *VehicleInfo) GetDatatype() string {
	if o == nil || IsNil(o.Datatype) {
		var ret string
		return ret
	}
	return *o.Datatype
}

// GetDatatypeOk returns a tuple with the Datatype field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VehicleInfo) GetDatatypeOk() (*string, bool) {
	if o == nil || IsNil(o.Datatype) {
		return nil, false
	}
	return o.Datatype, true
}

// HasDatatype returns a boolean if a field has been set.
func (o *VehicleInfo) HasDatatype() bool {
	if o != nil && !IsNil(o.Datatype) {
		return true
	}

	return false
}

// SetDatatype gets a reference to the given string and assigns it to the Datatype field.
func (o *VehicleInfo) SetDatatype(v string) {
	o.Datatype = &v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *VehicleInfo) GetOrder() int32 {
	if o == nil || IsNil(o.Order) {
		var ret int32
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VehicleInfo) GetOrderOk() (*int32, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *VehicleInfo) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given int32 and assigns it to the Order field.
func (o *VehicleInfo) SetOrder(v int32) {
	o.Order = &v
}

// GetRichtext returns the Richtext field value if set, zero value otherwise.
func (o *VehicleInfo) GetRichtext() []RichTextDTO {
	if o == nil || IsNil(o.Richtext) {
		var ret []RichTextDTO
		return ret
	}
	return o.Richtext
}

// GetRichtextOk returns a tuple with the Richtext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VehicleInfo) GetRichtextOk() ([]RichTextDTO, bool) {
	if o == nil || IsNil(o.Richtext) {
		return nil, false
	}
	return o.Richtext, true
}

// HasRichtext returns a boolean if a field has been set.
func (o *VehicleInfo) HasRichtext() bool {
	if o != nil && !IsNil(o.Richtext) {
		return true
	}

	return false
}

// SetRichtext gets a reference to the given []RichTextDTO and assigns it to the Richtext field.
func (o *VehicleInfo) SetRichtext(v []RichTextDTO) {
	o.Richtext = v
}

func (o VehicleInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VehicleInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Datatype) {
		toSerialize["datatype"] = o.Datatype
	}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	if !IsNil(o.Richtext) {
		toSerialize["richtext"] = o.Richtext
	}
	return toSerialize, nil
}

type NullableVehicleInfo struct {
	value *VehicleInfo
	isSet bool
}

func (v NullableVehicleInfo) Get() *VehicleInfo {
	return v.value
}

func (v *NullableVehicleInfo) Set(val *VehicleInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableVehicleInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableVehicleInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVehicleInfo(val *VehicleInfo) *NullableVehicleInfo {
	return &NullableVehicleInfo{value: val, isSet: true}
}

func (v NullableVehicleInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVehicleInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


