/*
Hella Gutmann - macsDS (Data Services) - API collection

This document contains all relevant APIs for diagnostics (incl. DTCs), repair & maintenance information (RMI) and vehicle identification.

API version: V20240702-130718
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github.com/binhatch/go-macds

import (
	"encoding/json"
)

// checks if the GuideReference type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GuideReference{}

// GuideReference struct for GuideReference
type GuideReference struct {
	ObjectReference *ObjectReference `json:"objectReference,omitempty"`
}

// NewGuideReference instantiates a new GuideReference object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGuideReference() *GuideReference {
	this := GuideReference{}
	return &this
}

// NewGuideReferenceWithDefaults instantiates a new GuideReference object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGuideReferenceWithDefaults() *GuideReference {
	this := GuideReference{}
	return &this
}

// GetObjectReference returns the ObjectReference field value if set, zero value otherwise.
func (o *GuideReference) GetObjectReference() ObjectReference {
	if o == nil || IsNil(o.ObjectReference) {
		var ret ObjectReference
		return ret
	}
	return *o.ObjectReference
}

// GetObjectReferenceOk returns a tuple with the ObjectReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuideReference) GetObjectReferenceOk() (*ObjectReference, bool) {
	if o == nil || IsNil(o.ObjectReference) {
		return nil, false
	}
	return o.ObjectReference, true
}

// HasObjectReference returns a boolean if a field has been set.
func (o *GuideReference) HasObjectReference() bool {
	if o != nil && !IsNil(o.ObjectReference) {
		return true
	}

	return false
}

// SetObjectReference gets a reference to the given ObjectReference and assigns it to the ObjectReference field.
func (o *GuideReference) SetObjectReference(v ObjectReference) {
	o.ObjectReference = &v
}

func (o GuideReference) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GuideReference) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ObjectReference) {
		toSerialize["objectReference"] = o.ObjectReference
	}
	return toSerialize, nil
}

type NullableGuideReference struct {
	value *GuideReference
	isSet bool
}

func (v NullableGuideReference) Get() *GuideReference {
	return v.value
}

func (v *NullableGuideReference) Set(val *GuideReference) {
	v.value = val
	v.isSet = true
}

func (v NullableGuideReference) IsSet() bool {
	return v.isSet
}

func (v *NullableGuideReference) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGuideReference(val *GuideReference) *NullableGuideReference {
	return &NullableGuideReference{value: val, isSet: true}
}

func (v NullableGuideReference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGuideReference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


