/*
Hella Gutmann - macsDS (Data Services) - API collection

This document contains all relevant APIs for diagnostics (incl. DTCs), repair & maintenance information (RMI) and vehicle identification.

API version: V20240702-130718
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github.com/binhatch/go-macds

import (
	"encoding/json"
)

// checks if the OrderedImage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderedImage{}

// OrderedImage struct for OrderedImage
type OrderedImage struct {
	// Order
	Order *int64 `json:"order,omitempty"`
	ObjectReference *ObjectReference `json:"objectReference,omitempty"`
}

// NewOrderedImage instantiates a new OrderedImage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderedImage() *OrderedImage {
	this := OrderedImage{}
	return &this
}

// NewOrderedImageWithDefaults instantiates a new OrderedImage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderedImageWithDefaults() *OrderedImage {
	this := OrderedImage{}
	return &this
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *OrderedImage) GetOrder() int64 {
	if o == nil || IsNil(o.Order) {
		var ret int64
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderedImage) GetOrderOk() (*int64, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *OrderedImage) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given int64 and assigns it to the Order field.
func (o *OrderedImage) SetOrder(v int64) {
	o.Order = &v
}

// GetObjectReference returns the ObjectReference field value if set, zero value otherwise.
func (o *OrderedImage) GetObjectReference() ObjectReference {
	if o == nil || IsNil(o.ObjectReference) {
		var ret ObjectReference
		return ret
	}
	return *o.ObjectReference
}

// GetObjectReferenceOk returns a tuple with the ObjectReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderedImage) GetObjectReferenceOk() (*ObjectReference, bool) {
	if o == nil || IsNil(o.ObjectReference) {
		return nil, false
	}
	return o.ObjectReference, true
}

// HasObjectReference returns a boolean if a field has been set.
func (o *OrderedImage) HasObjectReference() bool {
	if o != nil && !IsNil(o.ObjectReference) {
		return true
	}

	return false
}

// SetObjectReference gets a reference to the given ObjectReference and assigns it to the ObjectReference field.
func (o *OrderedImage) SetObjectReference(v ObjectReference) {
	o.ObjectReference = &v
}

func (o OrderedImage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderedImage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	if !IsNil(o.ObjectReference) {
		toSerialize["objectReference"] = o.ObjectReference
	}
	return toSerialize, nil
}

type NullableOrderedImage struct {
	value *OrderedImage
	isSet bool
}

func (v NullableOrderedImage) Get() *OrderedImage {
	return v.value
}

func (v *NullableOrderedImage) Set(val *OrderedImage) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderedImage) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderedImage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderedImage(val *OrderedImage) *NullableOrderedImage {
	return &NullableOrderedImage{value: val, isSet: true}
}

func (v NullableOrderedImage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderedImage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


