/*
Hella Gutmann - macsDS (Data Services) - API collection

This document contains all relevant APIs for diagnostics (incl. DTCs), repair & maintenance information (RMI) and vehicle identification.

API version: V20240702-130718
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go-macds

import (
	"encoding/json"
)

// checks if the ReplacementNameReference type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReplacementNameReference{}

// ReplacementNameReference struct for ReplacementNameReference
type ReplacementNameReference struct {
	TextReference *ReplacementTextReference `json:"textReference,omitempty"`
	// Order
	Order *int32 `json:"order,omitempty"`
}

// NewReplacementNameReference instantiates a new ReplacementNameReference object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReplacementNameReference() *ReplacementNameReference {
	this := ReplacementNameReference{}
	return &this
}

// NewReplacementNameReferenceWithDefaults instantiates a new ReplacementNameReference object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReplacementNameReferenceWithDefaults() *ReplacementNameReference {
	this := ReplacementNameReference{}
	return &this
}

// GetTextReference returns the TextReference field value if set, zero value otherwise.
func (o *ReplacementNameReference) GetTextReference() ReplacementTextReference {
	if o == nil || IsNil(o.TextReference) {
		var ret ReplacementTextReference
		return ret
	}
	return *o.TextReference
}

// GetTextReferenceOk returns a tuple with the TextReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReplacementNameReference) GetTextReferenceOk() (*ReplacementTextReference, bool) {
	if o == nil || IsNil(o.TextReference) {
		return nil, false
	}
	return o.TextReference, true
}

// HasTextReference returns a boolean if a field has been set.
func (o *ReplacementNameReference) HasTextReference() bool {
	if o != nil && !IsNil(o.TextReference) {
		return true
	}

	return false
}

// SetTextReference gets a reference to the given ReplacementTextReference and assigns it to the TextReference field.
func (o *ReplacementNameReference) SetTextReference(v ReplacementTextReference) {
	o.TextReference = &v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *ReplacementNameReference) GetOrder() int32 {
	if o == nil || IsNil(o.Order) {
		var ret int32
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReplacementNameReference) GetOrderOk() (*int32, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *ReplacementNameReference) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given int32 and assigns it to the Order field.
func (o *ReplacementNameReference) SetOrder(v int32) {
	o.Order = &v
}

func (o ReplacementNameReference) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReplacementNameReference) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TextReference) {
		toSerialize["textReference"] = o.TextReference
	}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	return toSerialize, nil
}

type NullableReplacementNameReference struct {
	value *ReplacementNameReference
	isSet bool
}

func (v NullableReplacementNameReference) Get() *ReplacementNameReference {
	return v.value
}

func (v *NullableReplacementNameReference) Set(val *ReplacementNameReference) {
	v.value = val
	v.isSet = true
}

func (v NullableReplacementNameReference) IsSet() bool {
	return v.isSet
}

func (v *NullableReplacementNameReference) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReplacementNameReference(val *ReplacementNameReference) *NullableReplacementNameReference {
	return &NullableReplacementNameReference{value: val, isSet: true}
}

func (v NullableReplacementNameReference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReplacementNameReference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


