/*
Hella Gutmann - macsDS (Data Services) - API collection

This document contains all relevant APIs for diagnostics (incl. DTCs), repair & maintenance information (RMI) and vehicle identification.

API version: V20240702-130718
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gomacds

import (
	"encoding/json"
)

// checks if the FuseBoxLocationsResponseDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FuseBoxLocationsResponseDTO{}

// FuseBoxLocationsResponseDTO struct for FuseBoxLocationsResponseDTO
type FuseBoxLocationsResponseDTO struct {
	// Id
	Id *int32 `json:"id,omitempty"`
	Name *Texts `json:"name,omitempty"`
	// Year From
	YearFrom *string `json:"yearFrom,omitempty"`
	// Year To
	YearTo *string `json:"yearTo,omitempty"`
	// Engine Code
	EngineCode *string `json:"engineCode,omitempty"`
	// Relays
	Relays []RelayDTO `json:"relays,omitempty"`
}

// NewFuseBoxLocationsResponseDTO instantiates a new FuseBoxLocationsResponseDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFuseBoxLocationsResponseDTO() *FuseBoxLocationsResponseDTO {
	this := FuseBoxLocationsResponseDTO{}
	return &this
}

// NewFuseBoxLocationsResponseDTOWithDefaults instantiates a new FuseBoxLocationsResponseDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFuseBoxLocationsResponseDTOWithDefaults() *FuseBoxLocationsResponseDTO {
	this := FuseBoxLocationsResponseDTO{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FuseBoxLocationsResponseDTO) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FuseBoxLocationsResponseDTO) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FuseBoxLocationsResponseDTO) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *FuseBoxLocationsResponseDTO) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FuseBoxLocationsResponseDTO) GetName() Texts {
	if o == nil || IsNil(o.Name) {
		var ret Texts
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FuseBoxLocationsResponseDTO) GetNameOk() (*Texts, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FuseBoxLocationsResponseDTO) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given Texts and assigns it to the Name field.
func (o *FuseBoxLocationsResponseDTO) SetName(v Texts) {
	o.Name = &v
}

// GetYearFrom returns the YearFrom field value if set, zero value otherwise.
func (o *FuseBoxLocationsResponseDTO) GetYearFrom() string {
	if o == nil || IsNil(o.YearFrom) {
		var ret string
		return ret
	}
	return *o.YearFrom
}

// GetYearFromOk returns a tuple with the YearFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FuseBoxLocationsResponseDTO) GetYearFromOk() (*string, bool) {
	if o == nil || IsNil(o.YearFrom) {
		return nil, false
	}
	return o.YearFrom, true
}

// HasYearFrom returns a boolean if a field has been set.
func (o *FuseBoxLocationsResponseDTO) HasYearFrom() bool {
	if o != nil && !IsNil(o.YearFrom) {
		return true
	}

	return false
}

// SetYearFrom gets a reference to the given string and assigns it to the YearFrom field.
func (o *FuseBoxLocationsResponseDTO) SetYearFrom(v string) {
	o.YearFrom = &v
}

// GetYearTo returns the YearTo field value if set, zero value otherwise.
func (o *FuseBoxLocationsResponseDTO) GetYearTo() string {
	if o == nil || IsNil(o.YearTo) {
		var ret string
		return ret
	}
	return *o.YearTo
}

// GetYearToOk returns a tuple with the YearTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FuseBoxLocationsResponseDTO) GetYearToOk() (*string, bool) {
	if o == nil || IsNil(o.YearTo) {
		return nil, false
	}
	return o.YearTo, true
}

// HasYearTo returns a boolean if a field has been set.
func (o *FuseBoxLocationsResponseDTO) HasYearTo() bool {
	if o != nil && !IsNil(o.YearTo) {
		return true
	}

	return false
}

// SetYearTo gets a reference to the given string and assigns it to the YearTo field.
func (o *FuseBoxLocationsResponseDTO) SetYearTo(v string) {
	o.YearTo = &v
}

// GetEngineCode returns the EngineCode field value if set, zero value otherwise.
func (o *FuseBoxLocationsResponseDTO) GetEngineCode() string {
	if o == nil || IsNil(o.EngineCode) {
		var ret string
		return ret
	}
	return *o.EngineCode
}

// GetEngineCodeOk returns a tuple with the EngineCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FuseBoxLocationsResponseDTO) GetEngineCodeOk() (*string, bool) {
	if o == nil || IsNil(o.EngineCode) {
		return nil, false
	}
	return o.EngineCode, true
}

// HasEngineCode returns a boolean if a field has been set.
func (o *FuseBoxLocationsResponseDTO) HasEngineCode() bool {
	if o != nil && !IsNil(o.EngineCode) {
		return true
	}

	return false
}

// SetEngineCode gets a reference to the given string and assigns it to the EngineCode field.
func (o *FuseBoxLocationsResponseDTO) SetEngineCode(v string) {
	o.EngineCode = &v
}

// GetRelays returns the Relays field value if set, zero value otherwise.
func (o *FuseBoxLocationsResponseDTO) GetRelays() []RelayDTO {
	if o == nil || IsNil(o.Relays) {
		var ret []RelayDTO
		return ret
	}
	return o.Relays
}

// GetRelaysOk returns a tuple with the Relays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FuseBoxLocationsResponseDTO) GetRelaysOk() ([]RelayDTO, bool) {
	if o == nil || IsNil(o.Relays) {
		return nil, false
	}
	return o.Relays, true
}

// HasRelays returns a boolean if a field has been set.
func (o *FuseBoxLocationsResponseDTO) HasRelays() bool {
	if o != nil && !IsNil(o.Relays) {
		return true
	}

	return false
}

// SetRelays gets a reference to the given []RelayDTO and assigns it to the Relays field.
func (o *FuseBoxLocationsResponseDTO) SetRelays(v []RelayDTO) {
	o.Relays = v
}

func (o FuseBoxLocationsResponseDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FuseBoxLocationsResponseDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.YearFrom) {
		toSerialize["yearFrom"] = o.YearFrom
	}
	if !IsNil(o.YearTo) {
		toSerialize["yearTo"] = o.YearTo
	}
	if !IsNil(o.EngineCode) {
		toSerialize["engineCode"] = o.EngineCode
	}
	if !IsNil(o.Relays) {
		toSerialize["relays"] = o.Relays
	}
	return toSerialize, nil
}

type NullableFuseBoxLocationsResponseDTO struct {
	value *FuseBoxLocationsResponseDTO
	isSet bool
}

func (v NullableFuseBoxLocationsResponseDTO) Get() *FuseBoxLocationsResponseDTO {
	return v.value
}

func (v *NullableFuseBoxLocationsResponseDTO) Set(val *FuseBoxLocationsResponseDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableFuseBoxLocationsResponseDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableFuseBoxLocationsResponseDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFuseBoxLocationsResponseDTO(val *FuseBoxLocationsResponseDTO) *NullableFuseBoxLocationsResponseDTO {
	return &NullableFuseBoxLocationsResponseDTO{value: val, isSet: true}
}

func (v NullableFuseBoxLocationsResponseDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFuseBoxLocationsResponseDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


