/*
Hella Gutmann - macsDS (Data Services) - API collection

This document contains all relevant APIs for diagnostics (incl. DTCs), repair & maintenance information (RMI) and vehicle identification.

API version: V20240702-130718
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gomacds

import (
	"encoding/json"
)

// checks if the Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Response{}

// Response struct for Response
type Response struct {
	// Status
	Status *int32 `json:"status,omitempty"`
	Error *Error `json:"error,omitempty"`
	// Page
	Page *int32 `json:"page,omitempty"`
	// Number of total items
	TotalItems *int32 `json:"totalItems,omitempty"`
	// Number of total pages
	TotalPages *int32 `json:"totalPages,omitempty"`
	// Response data array of objects
	Data []DtcDataResponseV4 `json:"data,omitempty"`
	// Array containing predicted components and further information.
	PredictedComponents []Component `json:"predictedComponents,omitempty"`
	FeatureImportance *FeatureImportance `json:"featureImportance,omitempty"`
	// Numerical index based on the number and severity of trouble codes (critical, warning)
	Criticality *float32 `json:"criticality,omitempty"`
	// Unique string which references the related request and response of the component prediction for tracking purpose.
	PredictionFeedbackReference *string `json:"predictionFeedbackReference,omitempty"`
}

// NewResponse instantiates a new Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponse() *Response {
	this := Response{}
	return &this
}

// NewResponseWithDefaults instantiates a new Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseWithDefaults() *Response {
	this := Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Response) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *Response) SetStatus(v int32) {
	o.Status = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *Response) GetError() Error {
	if o == nil || IsNil(o.Error) {
		var ret Error
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response) GetErrorOk() (*Error, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given Error and assigns it to the Error field.
func (o *Response) SetError(v Error) {
	o.Error = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *Response) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *Response) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *Response) SetPage(v int32) {
	o.Page = &v
}

// GetTotalItems returns the TotalItems field value if set, zero value otherwise.
func (o *Response) GetTotalItems() int32 {
	if o == nil || IsNil(o.TotalItems) {
		var ret int32
		return ret
	}
	return *o.TotalItems
}

// GetTotalItemsOk returns a tuple with the TotalItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response) GetTotalItemsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalItems) {
		return nil, false
	}
	return o.TotalItems, true
}

// HasTotalItems returns a boolean if a field has been set.
func (o *Response) HasTotalItems() bool {
	if o != nil && !IsNil(o.TotalItems) {
		return true
	}

	return false
}

// SetTotalItems gets a reference to the given int32 and assigns it to the TotalItems field.
func (o *Response) SetTotalItems(v int32) {
	o.TotalItems = &v
}

// GetTotalPages returns the TotalPages field value if set, zero value otherwise.
func (o *Response) GetTotalPages() int32 {
	if o == nil || IsNil(o.TotalPages) {
		var ret int32
		return ret
	}
	return *o.TotalPages
}

// GetTotalPagesOk returns a tuple with the TotalPages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response) GetTotalPagesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalPages) {
		return nil, false
	}
	return o.TotalPages, true
}

// HasTotalPages returns a boolean if a field has been set.
func (o *Response) HasTotalPages() bool {
	if o != nil && !IsNil(o.TotalPages) {
		return true
	}

	return false
}

// SetTotalPages gets a reference to the given int32 and assigns it to the TotalPages field.
func (o *Response) SetTotalPages(v int32) {
	o.TotalPages = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *Response) GetData() []DtcDataResponseV4 {
	if o == nil || IsNil(o.Data) {
		var ret []DtcDataResponseV4
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response) GetDataOk() ([]DtcDataResponseV4, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []DtcDataResponseV4 and assigns it to the Data field.
func (o *Response) SetData(v []DtcDataResponseV4) {
	o.Data = v
}

// GetPredictedComponents returns the PredictedComponents field value if set, zero value otherwise.
func (o *Response) GetPredictedComponents() []Component {
	if o == nil || IsNil(o.PredictedComponents) {
		var ret []Component
		return ret
	}
	return o.PredictedComponents
}

// GetPredictedComponentsOk returns a tuple with the PredictedComponents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response) GetPredictedComponentsOk() ([]Component, bool) {
	if o == nil || IsNil(o.PredictedComponents) {
		return nil, false
	}
	return o.PredictedComponents, true
}

// HasPredictedComponents returns a boolean if a field has been set.
func (o *Response) HasPredictedComponents() bool {
	if o != nil && !IsNil(o.PredictedComponents) {
		return true
	}

	return false
}

// SetPredictedComponents gets a reference to the given []Component and assigns it to the PredictedComponents field.
func (o *Response) SetPredictedComponents(v []Component) {
	o.PredictedComponents = v
}

// GetFeatureImportance returns the FeatureImportance field value if set, zero value otherwise.
func (o *Response) GetFeatureImportance() FeatureImportance {
	if o == nil || IsNil(o.FeatureImportance) {
		var ret FeatureImportance
		return ret
	}
	return *o.FeatureImportance
}

// GetFeatureImportanceOk returns a tuple with the FeatureImportance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response) GetFeatureImportanceOk() (*FeatureImportance, bool) {
	if o == nil || IsNil(o.FeatureImportance) {
		return nil, false
	}
	return o.FeatureImportance, true
}

// HasFeatureImportance returns a boolean if a field has been set.
func (o *Response) HasFeatureImportance() bool {
	if o != nil && !IsNil(o.FeatureImportance) {
		return true
	}

	return false
}

// SetFeatureImportance gets a reference to the given FeatureImportance and assigns it to the FeatureImportance field.
func (o *Response) SetFeatureImportance(v FeatureImportance) {
	o.FeatureImportance = &v
}

// GetCriticality returns the Criticality field value if set, zero value otherwise.
func (o *Response) GetCriticality() float32 {
	if o == nil || IsNil(o.Criticality) {
		var ret float32
		return ret
	}
	return *o.Criticality
}

// GetCriticalityOk returns a tuple with the Criticality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response) GetCriticalityOk() (*float32, bool) {
	if o == nil || IsNil(o.Criticality) {
		return nil, false
	}
	return o.Criticality, true
}

// HasCriticality returns a boolean if a field has been set.
func (o *Response) HasCriticality() bool {
	if o != nil && !IsNil(o.Criticality) {
		return true
	}

	return false
}

// SetCriticality gets a reference to the given float32 and assigns it to the Criticality field.
func (o *Response) SetCriticality(v float32) {
	o.Criticality = &v
}

// GetPredictionFeedbackReference returns the PredictionFeedbackReference field value if set, zero value otherwise.
func (o *Response) GetPredictionFeedbackReference() string {
	if o == nil || IsNil(o.PredictionFeedbackReference) {
		var ret string
		return ret
	}
	return *o.PredictionFeedbackReference
}

// GetPredictionFeedbackReferenceOk returns a tuple with the PredictionFeedbackReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response) GetPredictionFeedbackReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.PredictionFeedbackReference) {
		return nil, false
	}
	return o.PredictionFeedbackReference, true
}

// HasPredictionFeedbackReference returns a boolean if a field has been set.
func (o *Response) HasPredictionFeedbackReference() bool {
	if o != nil && !IsNil(o.PredictionFeedbackReference) {
		return true
	}

	return false
}

// SetPredictionFeedbackReference gets a reference to the given string and assigns it to the PredictionFeedbackReference field.
func (o *Response) SetPredictionFeedbackReference(v string) {
	o.PredictionFeedbackReference = &v
}

func (o Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.TotalItems) {
		toSerialize["totalItems"] = o.TotalItems
	}
	if !IsNil(o.TotalPages) {
		toSerialize["totalPages"] = o.TotalPages
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.PredictedComponents) {
		toSerialize["predictedComponents"] = o.PredictedComponents
	}
	if !IsNil(o.FeatureImportance) {
		toSerialize["featureImportance"] = o.FeatureImportance
	}
	if !IsNil(o.Criticality) {
		toSerialize["criticality"] = o.Criticality
	}
	if !IsNil(o.PredictionFeedbackReference) {
		toSerialize["predictionFeedbackReference"] = o.PredictionFeedbackReference
	}
	return toSerialize, nil
}

type NullableResponse struct {
	value *Response
	isSet bool
}

func (v NullableResponse) Get() *Response {
	return v.value
}

func (v *NullableResponse) Set(val *Response) {
	v.value = val
	v.isSet = true
}

func (v NullableResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponse(val *Response) *NullableResponse {
	return &NullableResponse{value: val, isSet: true}
}

func (v NullableResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


