/*
Hella Gutmann - macsDS (Data Services) - API collection

This document contains all relevant APIs for diagnostics (incl. DTCs), repair & maintenance information (RMI) and vehicle identification.

API version: V20240702-130718
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go-macds

import (
	"encoding/json"
)

// checks if the TranslationDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TranslationDTO{}

// TranslationDTO struct for TranslationDTO
type TranslationDTO struct {
	// Two characters defining the language code; allowed values: de, en, nl, zh, it, hu, hr, fr, fi, es, el, tr, da, sv, sk, cs, ru, ro, pt, pl
	Language *string `json:"language,omitempty"`
	// Text
	Text *string `json:"text,omitempty"`
}

// NewTranslationDTO instantiates a new TranslationDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTranslationDTO() *TranslationDTO {
	this := TranslationDTO{}
	return &this
}

// NewTranslationDTOWithDefaults instantiates a new TranslationDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTranslationDTOWithDefaults() *TranslationDTO {
	this := TranslationDTO{}
	return &this
}

// GetLanguage returns the Language field value if set, zero value otherwise.
func (o *TranslationDTO) GetLanguage() string {
	if o == nil || IsNil(o.Language) {
		var ret string
		return ret
	}
	return *o.Language
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranslationDTO) GetLanguageOk() (*string, bool) {
	if o == nil || IsNil(o.Language) {
		return nil, false
	}
	return o.Language, true
}

// HasLanguage returns a boolean if a field has been set.
func (o *TranslationDTO) HasLanguage() bool {
	if o != nil && !IsNil(o.Language) {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given string and assigns it to the Language field.
func (o *TranslationDTO) SetLanguage(v string) {
	o.Language = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *TranslationDTO) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranslationDTO) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *TranslationDTO) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *TranslationDTO) SetText(v string) {
	o.Text = &v
}

func (o TranslationDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TranslationDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Language) {
		toSerialize["language"] = o.Language
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	return toSerialize, nil
}

type NullableTranslationDTO struct {
	value *TranslationDTO
	isSet bool
}

func (v NullableTranslationDTO) Get() *TranslationDTO {
	return v.value
}

func (v *NullableTranslationDTO) Set(val *TranslationDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableTranslationDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableTranslationDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTranslationDTO(val *TranslationDTO) *NullableTranslationDTO {
	return &NullableTranslationDTO{value: val, isSet: true}
}

func (v NullableTranslationDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTranslationDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


