/*
Hella Gutmann - macsDS (Data Services) - API collection

This document contains all relevant APIs for diagnostics (incl. DTCs), repair & maintenance information (RMI) and vehicle identification.

API version: V20240702-130718
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go-macds

import (
	"encoding/json"
)

// checks if the Image type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Image{}

// Image struct for Image
type Image struct {
	ObjectReference *ObjectReference `json:"objectReference,omitempty"`
}

// NewImage instantiates a new Image object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImage() *Image {
	this := Image{}
	return &this
}

// NewImageWithDefaults instantiates a new Image object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageWithDefaults() *Image {
	this := Image{}
	return &this
}

// GetObjectReference returns the ObjectReference field value if set, zero value otherwise.
func (o *Image) GetObjectReference() ObjectReference {
	if o == nil || IsNil(o.ObjectReference) {
		var ret ObjectReference
		return ret
	}
	return *o.ObjectReference
}

// GetObjectReferenceOk returns a tuple with the ObjectReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Image) GetObjectReferenceOk() (*ObjectReference, bool) {
	if o == nil || IsNil(o.ObjectReference) {
		return nil, false
	}
	return o.ObjectReference, true
}

// HasObjectReference returns a boolean if a field has been set.
func (o *Image) HasObjectReference() bool {
	if o != nil && !IsNil(o.ObjectReference) {
		return true
	}

	return false
}

// SetObjectReference gets a reference to the given ObjectReference and assigns it to the ObjectReference field.
func (o *Image) SetObjectReference(v ObjectReference) {
	o.ObjectReference = &v
}

func (o Image) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Image) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ObjectReference) {
		toSerialize["objectReference"] = o.ObjectReference
	}
	return toSerialize, nil
}

type NullableImage struct {
	value *Image
	isSet bool
}

func (v NullableImage) Get() *Image {
	return v.value
}

func (v *NullableImage) Set(val *Image) {
	v.value = val
	v.isSet = true
}

func (v NullableImage) IsSet() bool {
	return v.isSet
}

func (v *NullableImage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImage(val *Image) *NullableImage {
	return &NullableImage{value: val, isSet: true}
}

func (v NullableImage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


