/*
Hella Gutmann - macsDS (Data Services) - API collection

This document contains all relevant APIs for diagnostics (incl. DTCs), repair & maintenance information (RMI) and vehicle identification.

API version: V20240702-130718
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github.com/binhatch/go-macds

import (
	"encoding/json"
)

// checks if the TextReference type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TextReference{}

// TextReference struct for TextReference
type TextReference struct {
	// Id
	Id *int64 `json:"id,omitempty"`
	// Text
	Text *string `json:"text,omitempty"`
}

// NewTextReference instantiates a new TextReference object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTextReference() *TextReference {
	this := TextReference{}
	return &this
}

// NewTextReferenceWithDefaults instantiates a new TextReference object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTextReferenceWithDefaults() *TextReference {
	this := TextReference{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TextReference) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextReference) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TextReference) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *TextReference) SetId(v int64) {
	o.Id = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *TextReference) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextReference) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *TextReference) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *TextReference) SetText(v string) {
	o.Text = &v
}

func (o TextReference) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TextReference) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	return toSerialize, nil
}

type NullableTextReference struct {
	value *TextReference
	isSet bool
}

func (v NullableTextReference) Get() *TextReference {
	return v.value
}

func (v *NullableTextReference) Set(val *TextReference) {
	v.value = val
	v.isSet = true
}

func (v NullableTextReference) IsSet() bool {
	return v.isSet
}

func (v *NullableTextReference) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTextReference(val *TextReference) *NullableTextReference {
	return &NullableTextReference{value: val, isSet: true}
}

func (v NullableTextReference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTextReference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


