/*
Hella Gutmann - macsDS (Data Services) - API collection

This document contains all relevant APIs for diagnostics (incl. DTCs), repair & maintenance information (RMI) and vehicle identification.

API version: V20240702-130718
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gomacds

import (
	"encoding/json"
)

// checks if the ContentSection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentSection{}

// ContentSection struct for ContentSection
type ContentSection struct {
	// Order
	Order *int32 `json:"order,omitempty"`
	// List of Content Columns
	ContentColumns []ContentColumn `json:"contentColumns,omitempty"`
}

// NewContentSection instantiates a new ContentSection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentSection() *ContentSection {
	this := ContentSection{}
	return &this
}

// NewContentSectionWithDefaults instantiates a new ContentSection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentSectionWithDefaults() *ContentSection {
	this := ContentSection{}
	return &this
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *ContentSection) GetOrder() int32 {
	if o == nil || IsNil(o.Order) {
		var ret int32
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentSection) GetOrderOk() (*int32, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *ContentSection) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given int32 and assigns it to the Order field.
func (o *ContentSection) SetOrder(v int32) {
	o.Order = &v
}

// GetContentColumns returns the ContentColumns field value if set, zero value otherwise.
func (o *ContentSection) GetContentColumns() []ContentColumn {
	if o == nil || IsNil(o.ContentColumns) {
		var ret []ContentColumn
		return ret
	}
	return o.ContentColumns
}

// GetContentColumnsOk returns a tuple with the ContentColumns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentSection) GetContentColumnsOk() ([]ContentColumn, bool) {
	if o == nil || IsNil(o.ContentColumns) {
		return nil, false
	}
	return o.ContentColumns, true
}

// HasContentColumns returns a boolean if a field has been set.
func (o *ContentSection) HasContentColumns() bool {
	if o != nil && !IsNil(o.ContentColumns) {
		return true
	}

	return false
}

// SetContentColumns gets a reference to the given []ContentColumn and assigns it to the ContentColumns field.
func (o *ContentSection) SetContentColumns(v []ContentColumn) {
	o.ContentColumns = v
}

func (o ContentSection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentSection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	if !IsNil(o.ContentColumns) {
		toSerialize["contentColumns"] = o.ContentColumns
	}
	return toSerialize, nil
}

type NullableContentSection struct {
	value *ContentSection
	isSet bool
}

func (v NullableContentSection) Get() *ContentSection {
	return v.value
}

func (v *NullableContentSection) Set(val *ContentSection) {
	v.value = val
	v.isSet = true
}

func (v NullableContentSection) IsSet() bool {
	return v.isSet
}

func (v *NullableContentSection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentSection(val *ContentSection) *NullableContentSection {
	return &NullableContentSection{value: val, isSet: true}
}

func (v NullableContentSection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentSection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


