/*
Hella Gutmann - macsDS (Data Services) - API collection

This document contains all relevant APIs for diagnostics (incl. DTCs), repair & maintenance information (RMI) and vehicle identification.

API version: V20240702-130718
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go-macds

import (
	"encoding/json"
)

// checks if the TitleText type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TitleText{}

// TitleText struct for TitleText
type TitleText struct {
	TextReference *IdTranslation `json:"textReference,omitempty"`
}

// NewTitleText instantiates a new TitleText object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTitleText() *TitleText {
	this := TitleText{}
	return &this
}

// NewTitleTextWithDefaults instantiates a new TitleText object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTitleTextWithDefaults() *TitleText {
	this := TitleText{}
	return &this
}

// GetTextReference returns the TextReference field value if set, zero value otherwise.
func (o *TitleText) GetTextReference() IdTranslation {
	if o == nil || IsNil(o.TextReference) {
		var ret IdTranslation
		return ret
	}
	return *o.TextReference
}

// GetTextReferenceOk returns a tuple with the TextReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TitleText) GetTextReferenceOk() (*IdTranslation, bool) {
	if o == nil || IsNil(o.TextReference) {
		return nil, false
	}
	return o.TextReference, true
}

// HasTextReference returns a boolean if a field has been set.
func (o *TitleText) HasTextReference() bool {
	if o != nil && !IsNil(o.TextReference) {
		return true
	}

	return false
}

// SetTextReference gets a reference to the given IdTranslation and assigns it to the TextReference field.
func (o *TitleText) SetTextReference(v IdTranslation) {
	o.TextReference = &v
}

func (o TitleText) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TitleText) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TextReference) {
		toSerialize["textReference"] = o.TextReference
	}
	return toSerialize, nil
}

type NullableTitleText struct {
	value *TitleText
	isSet bool
}

func (v NullableTitleText) Get() *TitleText {
	return v.value
}

func (v *NullableTitleText) Set(val *TitleText) {
	v.value = val
	v.isSet = true
}

func (v NullableTitleText) IsSet() bool {
	return v.isSet
}

func (v *NullableTitleText) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTitleText(val *TitleText) *NullableTitleText {
	return &NullableTitleText{value: val, isSet: true}
}

func (v NullableTitleText) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTitleText) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


