/*
Hella Gutmann - macsDS (Data Services) - API collection

This document contains all relevant APIs for diagnostics (incl. DTCs), repair & maintenance information (RMI) and vehicle identification.

API version: V20240702-130718
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gomacds

import (
	"encoding/json"
)

// checks if the Diagnoses type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Diagnoses{}

// Diagnoses struct for Diagnoses
type Diagnoses struct {
	// id
	Id *int32 `json:"id,omitempty"`
	// Can have values to further specify the data type presented. Can have values such as: flatrateunit (repair times), fuserelay, composition (placements and organisation of different elements on the vehicle), stco (ECU coding), periphery (relevant periphery components to the main component), wiringdiagram, techdata, \"techinfo\" (proprietary knowledge database of Hella Gutmann), \"componenttestvalues\", \"bulletin\", \"manual\", \"gdst\" (basic setting),  \"faultcode\", \"parameter\"
	Datatype *string `json:"datatype,omitempty"`
	// order
	Order *int32 `json:"order,omitempty"`
	// text
	Text *string `json:"text,omitempty"`
	// Contains structured texts to guide the interpretation of text values.
	Richtext []RichTextDTO `json:"richtext,omitempty"`
	// The name of the sub system
	TextSubSystem *string `json:"textSubSystem,omitempty"`
}

// NewDiagnoses instantiates a new Diagnoses object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiagnoses() *Diagnoses {
	this := Diagnoses{}
	return &this
}

// NewDiagnosesWithDefaults instantiates a new Diagnoses object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiagnosesWithDefaults() *Diagnoses {
	this := Diagnoses{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Diagnoses) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Diagnoses) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Diagnoses) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *Diagnoses) SetId(v int32) {
	o.Id = &v
}

// GetDatatype returns the Datatype field value if set, zero value otherwise.
func (o *Diagnoses) GetDatatype() string {
	if o == nil || IsNil(o.Datatype) {
		var ret string
		return ret
	}
	return *o.Datatype
}

// GetDatatypeOk returns a tuple with the Datatype field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Diagnoses) GetDatatypeOk() (*string, bool) {
	if o == nil || IsNil(o.Datatype) {
		return nil, false
	}
	return o.Datatype, true
}

// HasDatatype returns a boolean if a field has been set.
func (o *Diagnoses) HasDatatype() bool {
	if o != nil && !IsNil(o.Datatype) {
		return true
	}

	return false
}

// SetDatatype gets a reference to the given string and assigns it to the Datatype field.
func (o *Diagnoses) SetDatatype(v string) {
	o.Datatype = &v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *Diagnoses) GetOrder() int32 {
	if o == nil || IsNil(o.Order) {
		var ret int32
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Diagnoses) GetOrderOk() (*int32, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *Diagnoses) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given int32 and assigns it to the Order field.
func (o *Diagnoses) SetOrder(v int32) {
	o.Order = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *Diagnoses) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Diagnoses) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *Diagnoses) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *Diagnoses) SetText(v string) {
	o.Text = &v
}

// GetRichtext returns the Richtext field value if set, zero value otherwise.
func (o *Diagnoses) GetRichtext() []RichTextDTO {
	if o == nil || IsNil(o.Richtext) {
		var ret []RichTextDTO
		return ret
	}
	return o.Richtext
}

// GetRichtextOk returns a tuple with the Richtext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Diagnoses) GetRichtextOk() ([]RichTextDTO, bool) {
	if o == nil || IsNil(o.Richtext) {
		return nil, false
	}
	return o.Richtext, true
}

// HasRichtext returns a boolean if a field has been set.
func (o *Diagnoses) HasRichtext() bool {
	if o != nil && !IsNil(o.Richtext) {
		return true
	}

	return false
}

// SetRichtext gets a reference to the given []RichTextDTO and assigns it to the Richtext field.
func (o *Diagnoses) SetRichtext(v []RichTextDTO) {
	o.Richtext = v
}

// GetTextSubSystem returns the TextSubSystem field value if set, zero value otherwise.
func (o *Diagnoses) GetTextSubSystem() string {
	if o == nil || IsNil(o.TextSubSystem) {
		var ret string
		return ret
	}
	return *o.TextSubSystem
}

// GetTextSubSystemOk returns a tuple with the TextSubSystem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Diagnoses) GetTextSubSystemOk() (*string, bool) {
	if o == nil || IsNil(o.TextSubSystem) {
		return nil, false
	}
	return o.TextSubSystem, true
}

// HasTextSubSystem returns a boolean if a field has been set.
func (o *Diagnoses) HasTextSubSystem() bool {
	if o != nil && !IsNil(o.TextSubSystem) {
		return true
	}

	return false
}

// SetTextSubSystem gets a reference to the given string and assigns it to the TextSubSystem field.
func (o *Diagnoses) SetTextSubSystem(v string) {
	o.TextSubSystem = &v
}

func (o Diagnoses) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Diagnoses) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Datatype) {
		toSerialize["datatype"] = o.Datatype
	}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.Richtext) {
		toSerialize["richtext"] = o.Richtext
	}
	if !IsNil(o.TextSubSystem) {
		toSerialize["textSubSystem"] = o.TextSubSystem
	}
	return toSerialize, nil
}

type NullableDiagnoses struct {
	value *Diagnoses
	isSet bool
}

func (v NullableDiagnoses) Get() *Diagnoses {
	return v.value
}

func (v *NullableDiagnoses) Set(val *Diagnoses) {
	v.value = val
	v.isSet = true
}

func (v NullableDiagnoses) IsSet() bool {
	return v.isSet
}

func (v *NullableDiagnoses) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiagnoses(val *Diagnoses) *NullableDiagnoses {
	return &NullableDiagnoses{value: val, isSet: true}
}

func (v NullableDiagnoses) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiagnoses) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


